<?php

declare(strict_types=1);

// $Id: xoops_version.php,v 1.7 2003/02/12 11:39:13 okazu Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_LANMOD_NAME;
$modversion['version'] = 1.00;
$modversion['description'] = _MI_LANMOD_DESC;
$modversion['author'] = 'modified for x2:<br><A HREF=mailto:kuba1404@o2.pl>KubaZ</A> (kuba1404@o2.pl)<br><br>based on script from <A HREF="http://www.quiecom.com"> Quiecom developers</A>';
$modversion['credits'] = '';
$modversion['help'] = '';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'images/lanmod_slogo.png';
$modversion['dirname'] = 'LanMod';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'lan';
$modversion['tables'][1] = 'lan_spons';
$modversion['tables'][2] = 'lan_going';
$modversion['tables'][3] = 'lan_blockinfo';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

//$modversion['templates'][1]['file'] = 'guestbook_index.html';
//$modversion['templates'][1]['description'] = '';
//$modversion['templates'][2]['file'] = 'guestbook_new.html';
//$modversion['templates'][2]['description'] = '';
//$modversion['templates'][3]['file'] = 'xoopspoll_results.html';
//$modversion['templates'][3]['description'] = '';

//Blocks

$modversion['blocks'][1]['file'] = 'block_lan.php';
$modversion['blocks'][1]['name'] = 'LanMod';
$modversion['blocks'][1]['description'] = '';
$modversion['blocks'][1]['show_func'] = 'block_lan_show';
$modversion['blocks'][1]['template'] = 'block_lan.html';

// Menu
$modversion['hasMain'] = 1;
